# Generated by Django 5.2.1 on 2025-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
