# Generated by Django 5.2.1 on 2025-05-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_categorie_produit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
    ]
