# Generated by Django 5.2.1 on 2025-05-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='stock.produit')),
            ],
        ),
    ]
